### ISSUE TITLE
Not an issue - question on approach

### ISSUE THREAD

**Issue by johndpope** [mand-mobile/mand-mobile-issue-helper#2]
Is it possible to have code serve up desktop stuff and mobile stuff ? 
Should sites be duplicated and redirected? Thoughts ? 

Eg should I have a mobile.domain.com hosting mand-mobile vue template and regular site using other theme components? Thanks in advance

**Comment by xxyan0205** [comment]
> Is it possible to have code serve up desktop stuff and mobile stuff ?
Should sites be duplicated and redirected? Thoughts ?

You cant build desktop or mobile applications using JavaScript, HTML and CSS by a cross-platform framework  (eg [electronjs](https://electronjs.org/) and [react-native](https://github.com/facebook/react-native))).

**Comment by johndpope** [comment]
I wondered if the mand-Mobile vue code can dynamically accommodate for desktop browser. I don’t need a desktop app.

**Comment by xxyan0205** [comment]
> dynamically accommodate for desktop browser

It is only used to build a web app that run on mobile devices.

**Comment by johndpope** [comment]
Ok thx
